{
  "nbformat": 4,
  "nbformat_minor": 0,
  "metadata": {
    "colab": {
      "provenance": [],
      "authorship_tag": "ABX9TyPCzEWowJs9JfxgGBZc83A5",
      "include_colab_link": true
    },
    "kernelspec": {
      "name": "python3",
      "display_name": "Python 3"
    },
    "language_info": {
      "name": "python"
    }
  },
  "cells": [
    {
      "cell_type": "markdown",
      "metadata": {
        "id": "view-in-github",
        "colab_type": "text"
      },
      "source": [
        "<a href=\"https://colab.research.google.com/github/alvarezanagib/Reto_criptomonedas_Base/blob/main/app_py.ipynb\" target=\"_parent\"><img src=\"https://colab.research.google.com/assets/colab-badge.svg\" alt=\"Open In Colab\"/></a>"
      ]
    },
    {
      "cell_type": "code",
      "execution_count": null,
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/",
          "height": 383
        },
        "id": "jCBwlrtgFLMm",
        "outputId": "78da6ddd-89a0-4489-b467-de987305b1de"
      },
      "outputs": [
        {
          "output_type": "error",
          "ename": "ModuleNotFoundError",
          "evalue": "No module named 'streamlit'",
          "traceback": [
            "\u001b[0;31m---------------------------------------------------------------------------\u001b[0m",
            "\u001b[0;31mModuleNotFoundError\u001b[0m                       Traceback (most recent call last)",
            "\u001b[0;32m/tmp/ipykernel_1638/1149184053.py\u001b[0m in \u001b[0;36m<cell line: 0>\u001b[0;34m()\u001b[0m\n\u001b[1;32m      4\u001b[0m \u001b[0;31m# ============================================================\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m      5\u001b[0m \u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m----> 6\u001b[0;31m \u001b[0;32mimport\u001b[0m \u001b[0mstreamlit\u001b[0m \u001b[0;32mas\u001b[0m \u001b[0mst\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m      7\u001b[0m \u001b[0;32mimport\u001b[0m \u001b[0myfinance\u001b[0m \u001b[0;32mas\u001b[0m \u001b[0myf\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m      8\u001b[0m \u001b[0;32mimport\u001b[0m \u001b[0mpandas\u001b[0m \u001b[0;32mas\u001b[0m \u001b[0mpd\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n",
            "\u001b[0;31mModuleNotFoundError\u001b[0m: No module named 'streamlit'",
            "",
            "\u001b[0;31m---------------------------------------------------------------------------\u001b[0;32m\nNOTE: If your import is failing due to a missing package, you can\nmanually install dependencies using either !pip or !apt.\n\nTo view examples of installing some common dependencies, click the\n\"Open Examples\" button below.\n\u001b[0;31m---------------------------------------------------------------------------\u001b[0m\n"
          ],
          "errorDetails": {
            "actions": [
              {
                "action": "open_url",
                "actionText": "Open Examples",
                "url": "/notebooks/snippets/importing_libraries.ipynb"
              }
            ]
          }
        }
      ],
      "source": [
        "# ============================================================\n",
        "# 💓 PULSE FUND — Concurso Analítica Financiera ITM 2026\n",
        "# Estrategia: Momentum mensual + filtro de volatilidad\n",
        "# ============================================================\n",
        "\n",
        "import streamlit as st\n",
        "import yfinance as yf\n",
        "import pandas as pd\n",
        "import numpy as np\n",
        "import plotly.express as px\n",
        "import plotly.graph_objects as go\n",
        "from datetime import date, timedelta\n",
        "\n",
        "# ── Configuración ────────────────────────────────────────────\n",
        "st.set_page_config(\n",
        "    page_title=\" Pulse Fund\",\n",
        "    page_icon=\"💓\",\n",
        "    layout=\"wide\"\n",
        ")\n",
        "\n",
        "# ── Header ───────────────────────────────────────────────────\n",
        "st.title(\"Pulse Fund\")\n",
        "st.caption(\"Invertimos cuando el mercado tiene pulso fuerte. Cuando hay tormenta, esperamos.\")\n",
        "st.divider()\n",
        "\n",
        "# ============================================================\n",
        "# SIDEBAR — Controles interactivos\n",
        "# ============================================================\n",
        "st.sidebar.header(\"⚙️ Parámetros\")\n",
        "\n",
        "criptos_disponibles = {\n",
        "    \"Bitcoin (BTC)\":  \"BTC-USD\",\n",
        "    \"Ethereum (ETH)\": \"ETH-USD\",\n",
        "    \"Solana (SOL)\":   \"SOL-USD\"\n",
        "}\n",
        "\n",
        "criptos_seleccionadas = st.sidebar.multiselect(\n",
        "    \"Criptomonedas:\",\n",
        "    options=list(criptos_disponibles.keys()),\n",
        "    default=list(criptos_disponibles.keys())\n",
        ")\n",
        "tickers = [criptos_disponibles[c] for c in criptos_seleccionadas]\n",
        "\n",
        "fecha_inicio = st.sidebar.date_input(\n",
        "    \"Fecha inicio:\",\n",
        "    value=date(2023, 1, 1),\n",
        "    min_value=date(2018, 1, 1),\n",
        "    max_value=date.today() - timedelta(days=60)\n",
        ")\n",
        "fecha_fin = date.today()\n",
        "\n",
        "monto_inicial = st.sidebar.number_input(\n",
        "    \"Monto hipotético (USD):\",\n",
        "    min_value=100,\n",
        "    max_value=1_000_000,\n",
        "    value=10_000,\n",
        "    step=500\n",
        ")\n",
        "\n",
        "st.sidebar.divider()\n",
        "st.sidebar.subheader(\"🎯 Parámetros Pulse Fund\")\n",
        "\n",
        "ventana_momentum = st.sidebar.slider(\n",
        "    \"Ventana momentum (días):\",\n",
        "    min_value=30, max_value=90, value=60\n",
        ")\n",
        "umbral_volatilidad = st.sidebar.slider(\n",
        "    \"Umbral volatilidad (% diario):\",\n",
        "    min_value=1.0, max_value=10.0, value=6.0, step=0.5\n",
        ")\n",
        "ventana_volatilidad = 21\n",
        "costo_transaccion   = 0.001\n",
        "\n",
        "# ============================================================\n",
        "# CARGA DE DATOS\n",
        "# ============================================================\n",
        "if len(tickers) == 0:\n",
        "    st.warning(\"⚠️ Selecciona al menos una criptomoneda.\")\n",
        "    st.stop()\n",
        "\n",
        "@st.cache_data(ttl=3600)\n",
        "def cargar_datos(tickers, inicio, fin):\n",
        "    datos = yf.download(\n",
        "        tickers, start=inicio, end=fin,\n",
        "        interval=\"1d\", auto_adjust=True\n",
        "    )\n",
        "    if len(tickers) == 1:\n",
        "        datos.columns = pd.MultiIndex.from_product([datos.columns, tickers])\n",
        "    precios = datos[\"Close\"].copy()\n",
        "    precios.columns = [c.replace(\"-USD\", \"\") for c in precios.columns]\n",
        "    return precios.dropna()\n",
        "\n",
        "with st.spinner(\"📡 Descargando datos desde Yahoo Finance...\"):\n",
        "    precios = cargar_datos(tickers, fecha_inicio, fecha_fin)\n",
        "\n",
        "if precios.empty:\n",
        "    st.error(\"❌ No se pudieron cargar datos.\")\n",
        "    st.stop()\n",
        "\n",
        "# ============================================================\n",
        "# CÁLCULOS BASE\n",
        "# ============================================================\n",
        "retornos    = precios.pct_change().dropna()\n",
        "volatilidad = retornos.std() * np.sqrt(252)\n",
        "umbral_dec  = umbral_volatilidad / 100\n",
        "\n",
        "# Rendimiento acumulado\n",
        "factor_acum = (1 + retornos).cumprod()\n",
        "portafolio  = factor_acum * monto_inicial\n",
        "\n",
        "# Maximum Drawdown por cripto\n",
        "def calcular_drawdown(serie):\n",
        "    pico = serie.expanding().max()\n",
        "    return (serie - pico) / pico\n",
        "\n",
        "# ============================================================\n",
        "# CÁLCULOS ESTRATEGIA PULSE FUND\n",
        "# ============================================================\n",
        "momentum        = precios.pct_change(ventana_momentum)\n",
        "volatilidad_rod = retornos.rolling(ventana_volatilidad).std()\n",
        "\n",
        "# Señales mensuales\n",
        "dias_rebalanceo = precios.resample('MS').first().index\n",
        "señales_mensuales = {}\n",
        "\n",
        "for fecha_mes in dias_rebalanceo:\n",
        "    dias_disp = precios.index[precios.index >= fecha_mes]\n",
        "    if len(dias_disp) == 0:\n",
        "        continue\n",
        "    fecha_real = dias_disp[0]\n",
        "    try:\n",
        "        fila_mom = momentum.loc[fecha_real]\n",
        "        fila_vol = volatilidad_rod.loc[fecha_real]\n",
        "    except KeyError:\n",
        "        señales_mensuales[fecha_real] = \"EFECTIVO\"\n",
        "        continue\n",
        "\n",
        "    criptos_pos = fila_mom[fila_mom > 0]\n",
        "    if criptos_pos.empty:\n",
        "        señales_mensuales[fecha_real] = \"EFECTIVO\"\n",
        "        continue\n",
        "\n",
        "    mejor = criptos_pos.idxmax()\n",
        "    if mejor in fila_vol.index and pd.notna(fila_vol[mejor]):\n",
        "        if fila_vol[mejor] < umbral_dec:\n",
        "            señales_mensuales[fecha_real] = mejor.replace(\"-USD\", \"\")\n",
        "        else:\n",
        "            señales_mensuales[fecha_real] = \"EFECTIVO\"\n",
        "    else:\n",
        "        señales_mensuales[fecha_real] = \"EFECTIVO\"\n",
        "\n",
        "# Expandir señales a días\n",
        "señal_diaria = pd.Series(index=precios.index, dtype=str)\n",
        "fechas_ord   = sorted(señales_mensuales.keys())\n",
        "\n",
        "for i, f_ini in enumerate(fechas_ord):\n",
        "    f_fin = fechas_ord[i + 1] if i + 1 < len(fechas_ord) else None\n",
        "    if f_fin:\n",
        "        mask = (precios.index >= f_ini) & (precios.index < f_fin)\n",
        "    else:\n",
        "        mask = precios.index >= f_ini\n",
        "    señal_diaria[mask] = señales_mensuales[f_ini]\n",
        "\n",
        "señal_diaria = señal_diaria.fillna(\"EFECTIVO\")\n",
        "\n",
        "# Retornos con costos\n",
        "retornos_pulse    = pd.Series(index=retornos.index, dtype=float)\n",
        "posicion_anterior = \"EFECTIVO\"\n",
        "\n",
        "for fecha in retornos.index:\n",
        "    señal = señal_diaria[fecha]\n",
        "    costo = costo_transaccion if señal != posicion_anterior else 0.0\n",
        "    posicion_anterior = señal\n",
        "    retornos_pulse[fecha] = (0.0 if señal == \"EFECTIVO\"\n",
        "                             else retornos.loc[fecha, señal]) - costo\n",
        "\n",
        "# Portafolios acumulados\n",
        "acum_pulse = (1 + retornos_pulse).cumprod()\n",
        "acum_btc   = (1 + retornos[\"BTC\"]).cumprod() if \"BTC\" in retornos.columns else None\n",
        "acum_eth   = (1 + retornos[\"ETH\"]).cumprod() if \"ETH\" in retornos.columns else None\n",
        "\n",
        "# Métricas Pulse Fund\n",
        "retorno_total_pulse = (1 + retornos_pulse).prod() - 1\n",
        "vol_pulse           = retornos_pulse.std() * np.sqrt(252)\n",
        "dd_pulse_serie      = calcular_drawdown(acum_pulse)\n",
        "max_dd_pulse        = dd_pulse_serie.min()\n",
        "sharpe_pulse        = (retornos_pulse.mean() * 252) / (retornos_pulse.std() * np.sqrt(252))\n",
        "pct_efectivo        = (señal_diaria == \"EFECTIVO\").mean()\n",
        "\n",
        "colores = {\n",
        "    \"BTC\": \"#F7931A\",\n",
        "    \"ETH\": \"#627EEA\",\n",
        "    \"SOL\": \"#9945FF\",\n",
        "    \"💓 Pulse Fund\": \"#00FF88\"\n",
        "}\n",
        "\n",
        "# ============================================================\n",
        "# TABS\n",
        "# ============================================================\n",
        "tab1, tab2, tab3, tab4 = st.tabs([\n",
        "    \"📊 Análisis Base\",\n",
        "    \"🎯 Estrategia Pulse Fund\",\n",
        "    \"📉 Elemento Cripto\",\n",
        "    \"👤 Recomendación al Inversor\"\n",
        "])\n",
        "\n",
        "# ── TAB 1 — ANÁLISIS BASE ────────────────────────────────────\n",
        "with tab1:\n",
        "    st.header(\"📊 Análisis Base\")\n",
        "\n",
        "    # Métricas rápidas\n",
        "    cols = st.columns(len(precios.columns))\n",
        "    for i, cripto in enumerate(precios.columns):\n",
        "        precio_actual  = precios[cripto].iloc[-1]\n",
        "        retorno_period = precios[cripto].iloc[-1] / precios[cripto].iloc[0] - 1\n",
        "        cols[i].metric(\n",
        "            label=cripto,\n",
        "            value=f\"${precio_actual:,.0f}\",\n",
        "            delta=f\"{retorno_period:+.1%} en el período\"\n",
        "        )\n",
        "\n",
        "    st.divider()\n",
        "\n",
        "    # Precios históricos\n",
        "    fig1 = px.line(\n",
        "        precios, x=precios.index, y=precios.columns.tolist(),\n",
        "        title=\"Evolución de precios\",\n",
        "        labels={\"value\": \"Precio (USD)\", \"variable\": \"Cripto\"},\n",
        "        color_discrete_map=colores\n",
        "    )\n",
        "    fig1.update_layout(hovermode=\"x unified\", height=400)\n",
        "    st.plotly_chart(fig1, use_container_width=True)\n",
        "\n",
        "    # Precio rebase 100\n",
        "    precios_reb = (precios / precios.iloc[0]) * 100\n",
        "    fig2 = px.line(\n",
        "        precios_reb, x=precios_reb.index, y=precios_reb.columns.tolist(),\n",
        "        title=\"Rendimiento comparado (base 100)\",\n",
        "        labels={\"value\": \"Rendimiento\", \"variable\": \"Cripto\"},\n",
        "        color_discrete_map=colores\n",
        "    )\n",
        "    fig2.add_hline(y=100, line_dash=\"dash\", line_color=\"gray\")\n",
        "    fig2.update_layout(hovermode=\"x unified\", height=400)\n",
        "    st.plotly_chart(fig2, use_container_width=True)\n",
        "\n",
        "    col1, col2 = st.columns(2)\n",
        "\n",
        "    with col1:\n",
        "        # Volatilidad\n",
        "        vol_df = volatilidad.reset_index()\n",
        "        vol_df.columns = [\"Cripto\", \"Volatilidad\"]\n",
        "        fig3 = px.bar(\n",
        "            vol_df, x=\"Cripto\", y=\"Volatilidad\",\n",
        "            title=\"⚡ Volatilidad anualizada\",\n",
        "            color=\"Cripto\", color_discrete_map=colores,\n",
        "            text_auto=\".1%\"\n",
        "        )\n",
        "        fig3.update_layout(yaxis_tickformat=\".0%\", showlegend=False)\n",
        "        st.plotly_chart(fig3, use_container_width=True)\n",
        "\n",
        "    with col2:\n",
        "        # % días negativos\n",
        "        pct_neg = (retornos < 0).mean()\n",
        "        neg_df  = pct_neg.reset_index()\n",
        "        neg_df.columns = [\"Cripto\", \"Pct_Neg\"]\n",
        "        fig4 = px.bar(\n",
        "            neg_df, x=\"Cripto\", y=\"Pct_Neg\",\n",
        "            title=\"📊 % días con retorno negativo\",\n",
        "            color=\"Cripto\", color_discrete_map=colores,\n",
        "            text_auto=\".1%\"\n",
        "        )\n",
        "        fig4.update_layout(yaxis_tickformat=\".0%\", showlegend=False)\n",
        "        st.plotly_chart(fig4, use_container_width=True)\n",
        "\n",
        "    # Rendimiento acumulado\n",
        "    fig5 = px.line(\n",
        "        portafolio, x=portafolio.index, y=portafolio.columns.tolist(),\n",
        "        title=f\"💰 Valor de ${monto_inicial:,} invertidos\",\n",
        "        labels={\"value\": \"Valor (USD)\", \"variable\": \"Cripto\"},\n",
        "        color_discrete_map=colores\n",
        "    )\n",
        "    fig5.add_hline(y=monto_inicial, line_dash=\"dash\", line_color=\"gray\")\n",
        "    fig5.update_layout(hovermode=\"x unified\", height=400)\n",
        "    st.plotly_chart(fig5, use_container_width=True)\n",
        "\n",
        "    # Maximum Drawdown\n",
        "    fig6 = go.Figure()\n",
        "    for cripto in precios.columns:\n",
        "        dd = calcular_drawdown(precios[cripto])\n",
        "        fig6.add_trace(go.Scatter(\n",
        "            x=dd.index, y=dd, name=cripto,\n",
        "            line=dict(color=colores.get(cripto, \"#888\")),\n",
        "            fill=\"tozeroy\",\n",
        "            fillcolor=f\"rgba(128,128,128,0.1)\"\n",
        "        ))\n",
        "    fig6.update_layout(\n",
        "        title=\"📉 Maximum Drawdown histórico\",\n",
        "        yaxis_tickformat=\".0%\",\n",
        "        hovermode=\"x unified\", height=400\n",
        "    )\n",
        "    st.plotly_chart(fig6, use_container_width=True)\n",
        "\n",
        "    # Tabla resumen\n",
        "    st.subheader(\"📋 Resumen de métricas\")\n",
        "    retorno_tot = (precios.iloc[-1] / precios.iloc[0] - 1)\n",
        "    resumen = pd.DataFrame({\n",
        "        \"Retorno total\":     retorno_tot.map(\"{:+.1%}\".format),\n",
        "        \"Volatilidad anual\": volatilidad.map(\"{:.1%}\".format),\n",
        "        \"Max Drawdown\":      {c: f\"{calcular_drawdown(precios[c]).min():.1%}\"\n",
        "                              for c in precios.columns},\n",
        "        \"% Días negativos\":  (retornos < 0).mean().map(\"{:.1%}\".format)\n",
        "    })\n",
        "    st.dataframe(resumen, use_container_width=True)\n",
        "\n",
        "# ── TAB 2 — ESTRATEGIA ───────────────────────────────────────\n",
        "with tab2:\n",
        "    st.header(\"🎯 Estrategia Pulse Fund\")\n",
        "\n",
        "    # Métricas principales\n",
        "    c1, c2, c3, c4 = st.columns(4)\n",
        "    c1.metric(\"Retorno Pulse Fund\", f\"{retorno_total_pulse:+.1%}\")\n",
        "    c2.metric(\"Max Drawdown\",       f\"{max_dd_pulse:.1%}\")\n",
        "    c3.metric(\"Sharpe Ratio\",       f\"{sharpe_pulse:.2f}\")\n",
        "    c4.metric(\"Tiempo en efectivo\", f\"{pct_efectivo:.1%}\")\n",
        "\n",
        "    st.divider()\n",
        "\n",
        "    # Backtesting\n",
        "    bt_df = pd.DataFrame({\n",
        "        \"💓 Pulse Fund\":     acum_pulse * monto_inicial,\n",
        "    })\n",
        "    if acum_btc is not None:\n",
        "        bt_df[\"🟠 Buy & Hold BTC\"] = acum_btc * monto_inicial\n",
        "    if acum_eth is not None:\n",
        "        bt_df[\"🔵 Buy & Hold ETH\"] = acum_eth * monto_inicial\n",
        "\n",
        "    bt_df = bt_df.dropna()\n",
        "    fig7  = px.line(\n",
        "        bt_df, x=bt_df.index, y=bt_df.columns.tolist(),\n",
        "        title=f\"🎯 Backtesting — ${monto_inicial:,} iniciales\",\n",
        "        labels={\"value\": \"Valor (USD)\", \"variable\": \"Estrategia\"},\n",
        "        color_discrete_map={\n",
        "            \"💓 Pulse Fund\":     \"#00FF88\",\n",
        "            \"🟠 Buy & Hold BTC\": \"#F7931A\",\n",
        "            \"🔵 Buy & Hold ETH\": \"#627EEA\"\n",
        "        }\n",
        "    )\n",
        "    fig7.add_hline(y=monto_inicial, line_dash=\"dash\", line_color=\"gray\")\n",
        "    fig7.update_layout(hovermode=\"x unified\", height=450)\n",
        "    st.plotly_chart(fig7, use_container_width=True)\n",
        "\n",
        "    # Tabla comparativa\n",
        "    def metricas_serie(serie, nombre):\n",
        "        ret   = (1 + serie).prod() - 1\n",
        "        vol   = serie.std() * np.sqrt(252)\n",
        "        acum  = (1 + serie).cumprod()\n",
        "        dd    = ((acum - acum.expanding().max()) / acum.expanding().max()).min()\n",
        "        sh    = (serie.mean() * 252) / (serie.std() * np.sqrt(252))\n",
        "        return {\"Estrategia\": nombre,\n",
        "                \"Retorno total\": f\"{ret:+.1%}\",\n",
        "                \"Volatilidad\":   f\"{vol:.1%}\",\n",
        "                \"Max Drawdown\":  f\"{dd:.1%}\",\n",
        "                \"Sharpe Ratio\":  f\"{sh:.2f}\"}\n",
        "\n",
        "    rows = [metricas_serie(retornos_pulse, \"💓 Pulse Fund\")]\n",
        "    if \"BTC\" in retornos.columns:\n",
        "        rows.append(metricas_serie(retornos[\"BTC\"], \"🟠 Buy & Hold BTC\"))\n",
        "    if \"ETH\" in retornos.columns:\n",
        "        rows.append(metricas_serie(retornos[\"ETH\"], \"🔵 Buy & Hold ETH\"))\n",
        "\n",
        "    st.dataframe(\n",
        "        pd.DataFrame(rows).set_index(\"Estrategia\"),\n",
        "        use_container_width=True\n",
        "    )\n",
        "\n",
        "    # Distribución de señales\n",
        "    conteo = señal_diaria.value_counts()\n",
        "    fig8   = px.bar(\n",
        "        x=conteo.index, y=conteo.values,\n",
        "        title=\"📊 Días en cada posición\",\n",
        "        labels={\"x\": \"Posición\", \"y\": \"Días\"},\n",
        "        color=conteo.index,\n",
        "        color_discrete_map={\n",
        "            \"BTC\": \"#F7931A\", \"ETH\": \"#627EEA\",\n",
        "            \"SOL\": \"#9945FF\", \"EFECTIVO\": \"#444444\"\n",
        "        },\n",
        "        text_auto=True\n",
        "    )\n",
        "    fig8.update_layout(showlegend=False, height=350)\n",
        "    st.plotly_chart(fig8, use_container_width=True)\n",
        "\n",
        "# ── TAB 3 — ELEMENTO CRIPTO ──────────────────────────────────\n",
        "with tab3:\n",
        "    st.header(\"📉 Caídas Extremas y Recuperación Post-Crash\")\n",
        "    st.caption(\"Análisis específico del ecosistema cripto — mercado 24/7 con crashes frecuentes\")\n",
        "\n",
        "    UMBRAL_CRASH = 0.20\n",
        "    crashes_list = []\n",
        "\n",
        "    for cripto in precios.columns:\n",
        "        p      = precios[cripto]\n",
        "        pico_h = p.expanding().max()\n",
        "        dd_s   = (p - pico_h) / pico_h\n",
        "        en_crash   = dd_s <= -UMBRAL_CRASH\n",
        "        ini_crash  = en_crash & ~en_crash.shift(1).fillna(False)\n",
        "\n",
        "        for f_ini in p.index[ini_crash]:\n",
        "            precio_pico  = pico_h[f_ini]\n",
        "            post         = p[f_ini:]\n",
        "            f_valle      = post.idxmin()\n",
        "            caida        = (post.min() - precio_pico) / precio_pico\n",
        "            recuperacion = p[f_valle:]\n",
        "            rec          = recuperacion[recuperacion >= precio_pico]\n",
        "            dias_rec     = (rec.index[0] - f_valle).days if len(rec) > 0 else None\n",
        "            crashes_list.append({\n",
        "                \"Cripto\":       cripto,\n",
        "                \"Inicio crash\": f_ini.date(),\n",
        "                \"Valle\":        f_valle.date(),\n",
        "                \"Caída máxima\": f\"{caida:.1%}\",\n",
        "                \"Días recuperación\": f\"{dias_rec} días\" if dias_rec else \"Aún no recuperado\"\n",
        "            })\n",
        "\n",
        "    crashes_df = pd.DataFrame(crashes_list)\n",
        "    if not crashes_df.empty:\n",
        "        st.dataframe(crashes_df, use_container_width=True)\n",
        "\n",
        "    # Drawdown con umbral\n",
        "    fig9 = go.Figure()\n",
        "    fill_colors = {\n",
        "        \"BTC\": \"rgba(247,147,26,0.15)\",\n",
        "        \"ETH\": \"rgba(98,126,234,0.15)\",\n",
        "        \"SOL\": \"rgba(153,69,255,0.15)\"\n",
        "    }\n",
        "    for cripto in precios.columns:\n",
        "        dd = calcular_drawdown(precios[cripto])\n",
        "        fig9.add_trace(go.Scatter(\n",
        "            x=dd.index, y=dd, name=cripto,\n",
        "            line=dict(color=colores.get(cripto, \"#888\"), width=2),\n",
        "            fill=\"tozeroy\",\n",
        "            fillcolor=fill_colors.get(cripto, \"rgba(128,128,128,0.1)\")\n",
        "        ))\n",
        "    fig9.add_hline(\n",
        "        y=-UMBRAL_CRASH, line_dash=\"dash\", line_color=\"red\",\n",
        "        annotation_text=\"Umbral crash -20%\"\n",
        "    )\n",
        "    fig9.update_layout(\n",
        "        title=\"Drawdown histórico y zonas de crash\",\n",
        "        yaxis_tickformat=\".0%\",\n",
        "        hovermode=\"x unified\", height=430\n",
        "    )\n",
        "    st.plotly_chart(fig9, use_container_width=True)\n",
        "\n",
        "    # Correlación\n",
        "    st.subheader(\"🔗 Correlación entre criptomonedas\")\n",
        "    corr = retornos.corr()\n",
        "    fig10 = px.imshow(\n",
        "        corr, title=\"Correlación de retornos diarios\",\n",
        "        color_continuous_scale=\"RdYlGn\",\n",
        "        zmin=-1, zmax=1, text_auto=\".2f\"\n",
        "    )\n",
        "    fig10.update_layout(height=380)\n",
        "    st.plotly_chart(fig10, use_container_width=True)\n",
        "\n",
        "    st.info(\"💡 Alta correlación entre criptos justifica la rotación de Pulse Fund — \"\n",
        "            \"si todas se mueven igual, elegir la más fuerte en cada momento es la estrategia óptima.\")\n",
        "\n",
        "# ── TAB 4 — RECOMENDACIÓN ────────────────────────────────────\n",
        "with tab4:\n",
        "    st.header(\"👤 Recomendación al Inversor\")\n",
        "\n",
        "    perfil = st.radio(\n",
        "        \"Selecciona tu perfil:\",\n",
        "        [\"🛡️ Conservador\", \"⚖️ Moderado\", \"🚀 Agresivo\"],\n",
        "        horizontal=True\n",
        "    )\n",
        "\n",
        "    st.divider()\n",
        "\n",
        "    if \"Conservador\" in perfil:\n",
        "        st.subheader(\"🛡️ Perfil Conservador — Protección del capital\")\n",
        "        col1, col2 = st.columns(2)\n",
        "        col1.metric(\"Max Drawdown Pulse Fund\", f\"{max_dd_pulse:.1%}\")\n",
        "        if acum_btc is not None:\n",
        "            dd_btc_val = calcular_drawdown(acum_btc).min()\n",
        "            col2.metric(\"Max Drawdown BTC\",        f\"{dd_btc_val:.1%}\",\n",
        "                        delta=f\"{max_dd_pulse - dd_btc_val:+.1%} vs BTC\",\n",
        "                        delta_color=\"inverse\")\n",
        "        st.info(f\"💡 En el peor momento, Pulse Fund perdió **{abs(max_dd_pulse):.1%}** \"\n",
        "                f\"vs **{abs(dd_btc_val):.1%}** del Buy & Hold BTC. \"\n",
        "                f\"El filtro de volatilidad protegió el capital.\")\n",
        "\n",
        "        fig_c = go.Figure()\n",
        "        fig_c.add_trace(go.Scatter(\n",
        "            x=dd_pulse_serie.index, y=dd_pulse_serie,\n",
        "            name=\"💓 Pulse Fund\", line=dict(color=\"#00FF88\", width=2),\n",
        "            fill=\"tozeroy\", fillcolor=\"rgba(0,255,136,0.1)\"\n",
        "        ))\n",
        "        if acum_btc is not None:\n",
        "            dd_btc_s = calcular_drawdown(acum_btc)\n",
        "            fig_c.add_trace(go.Scatter(\n",
        "                x=dd_btc_s.index, y=dd_btc_s,\n",
        "                name=\"🟠 BTC\", line=dict(color=\"#F7931A\", width=2),\n",
        "                fill=\"tozeroy\", fillcolor=\"rgba(247,147,26,0.1)\"\n",
        "            ))\n",
        "        fig_c.update_layout(\n",
        "            title=\"Comparación de pérdidas máximas\",\n",
        "            yaxis_tickformat=\".0%\", hovermode=\"x unified\", height=400\n",
        "        )\n",
        "        st.plotly_chart(fig_c, use_container_width=True)\n",
        "\n",
        "    elif \"Moderado\" in perfil:\n",
        "        st.subheader(\"⚖️ Perfil Moderado — Balance riesgo-retorno\")\n",
        "        col1, col2, col3 = st.columns(3)\n",
        "        col1.metric(\"Retorno Pulse Fund\",  f\"{retorno_total_pulse:+.1%}\")\n",
        "        col2.metric(\"Sharpe Ratio\",        f\"{sharpe_pulse:.2f}\")\n",
        "        col3.metric(\"Volatilidad\",         f\"{vol_pulse:.1%}\")\n",
        "        st.info(f\"💡 Pulse Fund creció **{retorno_total_pulse:+.1%}** desde {fecha_inicio} \"\n",
        "                f\"con un Sharpe Ratio de **{sharpe_pulse:.2f}** — \"\n",
        "                f\"buena calidad de retorno ajustado por riesgo.\")\n",
        "\n",
        "        fig_m = go.Figure()\n",
        "        fig_m.add_trace(go.Scatter(\n",
        "            x=acum_pulse.index, y=acum_pulse * monto_inicial,\n",
        "            name=\"💓 Pulse Fund\", line=dict(color=\"#00FF88\", width=3)\n",
        "        ))\n",
        "        if acum_btc is not None:\n",
        "            fig_m.add_trace(go.Scatter(\n",
        "                x=acum_btc.index, y=acum_btc * monto_inicial,\n",
        "                name=\"🟠 BTC\", line=dict(color=\"#F7931A\", width=2, dash=\"dash\")\n",
        "            ))\n",
        "        fig_m.add_hline(y=monto_inicial, line_dash=\"dot\", line_color=\"gray\")\n",
        "        fig_m.update_layout(\n",
        "            title=f\"Crecimiento de ${monto_inicial:,}\",\n",
        "            yaxis_tickprefix=\"$\", yaxis_tickformat=\",.0f\",\n",
        "            hovermode=\"x unified\", height=400\n",
        "        )\n",
        "        st.plotly_chart(fig_m, use_container_width=True)\n",
        "\n",
        "    else:\n",
        "        st.subheader(\"🚀 Perfil Agresivo — Máximo momentum\")\n",
        "        col1, col2 = st.columns(2)\n",
        "        col1.metric(\"Retorno Pulse Fund\", f\"{retorno_total_pulse:+.1%}\")\n",
        "        col2.metric(\"Tiempo invertido\",   f\"{1-pct_efectivo:.1%}\")\n",
        "        st.info(\"💡 Pulse Fund rota cada mes hacia la cripto con mayor momentum. \"\n",
        "                \"Siempre estás en la más fuerte — no en una sola.\")\n",
        "\n",
        "        conteo_agr = señal_diaria.value_counts()\n",
        "        fig_a = px.pie(\n",
        "            values=conteo_agr.values,\n",
        "            names=conteo_agr.index,\n",
        "            title=\"Distribución de tiempo por posición\",\n",
        "            color=conteo_agr.index,\n",
        "            color_discrete_map={\n",
        "                \"BTC\": \"#F7931A\", \"ETH\": \"#627EEA\",\n",
        "                \"SOL\": \"#9945FF\", \"EFECTIVO\": \"#444444\"\n",
        "            }\n",
        "        )\n",
        "        fig_a.update_traces(textinfo=\"label+percent\")\n",
        "        fig_a.update_layout(height=400)\n",
        "        st.plotly_chart(fig_a, use_container_width=True)\n",
        "\n",
        "# ============================================================\n",
        "# DISCLAIMER IA\n",
        "# ============================================================\n",
        "st.divider()\n",
        "st.caption(\n",
        "    \"**Disclaimer IA:** Claude Sonnet (Anthropic) — asistencia en estructura del código, \"\n",
        "    \"lógica de backtesting y visualizaciones | \"\n",
        "    \"El equipo Pulse Fund definió la estrategia de inversión, validó todos los cálculos \"\n",
        "    \"y tomó las decisiones analíticas.\"\n",
        ")"
      ]
    }
  ]
}
